#+TITLE: 蜀山剑士
#+OPTIONS: ^:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">
* 初来乍到
随着一声汽笛，火车缓缓驶入龙门南站[fn:1]。

从闷热的车厢走出来，迎面而来的是龙门潮湿而燠热的空气，混杂着车站来往人群的气息。绕是如此，张一零还是深吸了一口气。

这就是龙门，商业之都，独立之地，未来四年——也许不止四年，张一零都要居住在这个城市里面。

张一零紧一紧行囊，走出火车站。必要的证件、几套换洗的衣物，还有一把剑，就是他的全部行李，亡父的遗产早已存入银行，他手头的零钱不多。

刚走到火车站广场，正在东张西望的张一零被一个人撞个正着。张一零没什么事，撞他的人却摔倒在地，仔细一看，是一个衣衫褴褛面黄肌瘦、嘴边还流着血的少年。

摔倒在地的少年喘着大气望向张一零。张一零正要把他扶起来，一个暴怒的声音传来：「贱狗，让我逮着你了。」

张一零把地上的少年拉起来，循声望去，一个穿着华服的贵族少年怒不可遏地走来。

张一零把少年拉到自己身后，迎向那个贵族少年，问：「他偷你东西了？」

「你是什么人，敢管我的闲事？」

真是一个不好回答的问题，张一零暗想，同时大量了一下眼前贵族的服饰：「如果他偷了你的东西，我跟你一起送他去警察局。如果他没有，我倒想问问你为什么打他。」

「我……没偷东西。」身后的少年虚弱地说。

「他撞倒我了，还敢跑！」

见鬼，居然有这么不讲理的人。估计不打一架好不了。张一零暗叫头痛：「这不是你打他的理由。」

「你找死！」贵族少年大喝一声，挥拳打来，动作迅猛，而且用上了术法。

张一零左手一拂，挡开了这一拳。贵族少年趁势一退，但仍不肯甘休，屈膝蓄力，使出了更刚猛的一拳。张一零右手挥掌挡下拳头，引导术元入体，正是万剑诀中的轮回诀。

然而术元甫一入体，张一零便知不妙，对手有秘传的术法，入体的术元有独特的结构，使之可以延时爆开，这一下，张一零如遭重击，顿觉五脏六腑仿如沸腾。

他运起术元，平抑痛觉，左脚弓步，右脚跨出一步，左手成掌护住胸前，右手伸出，掌心向上。然后他右手食指勾起，挑衅地说：「再来！」

贵族少年冷笑一声，再度进攻。

* Footnotes

[fn:1] 无容置疑，这是以《明日方舟》 的龙门作为蓝本的一个城市。
