#+TITLE: 蜀山剑士
#+OPTIONS: ^:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">
* 初来乍到
随着一声汽笛，火车缓缓驶入龙门南站[fn:1]。

从闷热的车厢走出来，迎面而来的是龙门潮湿而燠热的空气，混杂着车站来往人群的气息。绕是如此，张一零还是深吸了一口气。

这就是龙门，商业之都，独立之地，未来四年——也许不止四年，张一零都要居住在这个城市里面。

张一零紧一紧行囊，走出火车站。必要的证件、几套换洗的衣物，还有一把剑，就是他的全部行李，亡父的遗产早已存入银行，他手头的零钱不多。

刚走到火车站广场，正在东张西望的张一零被一个人撞个正着。张一零没什么事，撞他的人却摔倒在地，仔细一看，是一个衣衫褴褛面黄肌瘦、嘴边还流着血的少年。

摔倒在地的少年喘着大气望向张一零。张一零正要把他扶起来，一个暴怒的声音传来：「贱狗，让我逮着你了。」

张一零把地上的少年拉起来，循声望去，一个穿着华服的贵族少年怒不可遏地走来。

张一零把少年拉到自己身后，迎向那个贵族少年，问：「他偷你东西了？」

「你是什么人，敢管我的闲事？」

真是一个不好回答的问题[fn:2]，张一零暗想，同时打量了一下眼前贵族的服饰：「如果他偷了你的东西，我跟你一起送他去警察局。如果他没有，我倒想问问你为什么打他。」

「我……没偷东西。」身后的少年虚弱地说。

「他撞倒我了，还敢跑！」

见鬼，居然有这么不讲理的人。估计不打一架好不了。张一零暗叫头痛：「这不是你打他的理由。」

「你找死！」贵族少年大喝一声，挥拳打来，动作迅猛，而且用上了术法。

张一零左手一拂，挡开了这一拳。贵族少年趁势一退，但仍不肯甘休，屈膝蓄力，使出了更刚猛的一拳。张一零右手挥掌挡下拳头，引导术元入体，正是万剑诀中的轮回诀。

然而术元甫一入体，张一零便知不妙，对手有秘传的术法，入体的术元有独特的结构，使之可以延时爆开，这一下，张一零如遭重击，顿觉五脏六腑仿如沸腾。

他运起术元，平抑痛觉，左脚弓步，右脚跨出一步，左手成掌护住胸前，右手伸出，掌心向上。然后他右手食指勾起，挑衅地说：「再来！」

贵族少年冷笑一声，再度进攻。这一拳不比平常，破风之声呼啸而来。张一零右掌迎上，并不硬接，而是顺势牵动对手的拳劲，纳术元入体，与此同时也把自己的术元注入对方的术元中。轮回诀运化一周天之后再把对方的术元转到左手，以无双诀打出。这是万剑诀的一套综合应用——「归一入轮回，再世现无双」。轮回诀吸收对手术元时，用归一诀注入自己的术元，破坏对手术元的结构，化消之后再用无双诀打出。这门技术在好一点的中学都会教导，不过掌握起来不容易。

张一零的左拳更快，威力更强——其实他可以把术元集中在食指和中指，但是他只用拳头，毕竟不是生死搏斗，给对方一个教训就够了。

但是一个黑衣人横里冲了出来，用右臂挡住了张一零反击的一拳。双方术元的冲击把张一零震了回来。是高手。对手毫无花巧地接下这一拳，张一零心知不妙，还没站稳，又向侧后方急退。但是对手依然追击，左拳怒击而来。

方才那个贵族少年的一拳，无论力量还是速度，与这一拳都不可同日而语，张一零看得见，但是避不开，也不敢用轮回诀，如果硬接，感觉得吃大亏。

千钧一发之际，一只巨掌挡下了这一拳。黑衣人也像张一零一样急退回贵族少年身边。

是一个身高不下两米的大汉，宛如铁塔般站在一旁，左手提着行李，右手伸出，挡在张一零和黑衣人之间。

张一零偷眼观瞧，那大汉五十上下年龄，黑发已经斑白，但他认出对方，顿时安心下来。

大汉发话了：「得了，两个小孩切磋切磋，你一大人掺合进来就不合适了。」

贵族少年正要发话，黑衣人制止了他，说：「我是保镖，职责所在。」

「挡那一拳是职责，再来追击就不是了。」

「阁下想怎样？」

大汉望了张一零和那个少年一眼，说：「大路朝天，各走一边吧，别在这耽搁人家的路。」

黑衣人按住贵族少年肩头，少年虽然不忿，但不太闹腾。然后黑衣人朝大汉一拱手，带着贵族少年走了。

围观的众人见事情过去了，也渐渐散去。

大汉回头对张一零说：「行啊小子，挺楞的呀！知道他是谁吗，就敢出手？」

张一零说：「看纹章是卡西米尔锈铜家族的旁支，要是他们能隔着维多利亚在龙门打我黑棍，我也佩服他们。更何况，大名鼎鼎的战争英雄博卓卡斯替[fn:3]站出来帮我撑腰，还用怕他吗？」

被称为「博卓卡斯替」的大汉笑了一下，说：「那我没有来呢？」

「那我也得咬一口再逃，不能让他们觉得我是好欺负的。」

博卓卡斯替不置可否，俯身问瘦弱的少年：「你叫什么名字？住在哪里？」

那少年没有说他的名字，只是说他住在城寨。博卓卡斯替也不追问，只对张一零说：「咱把他送回去吧。」

张一零答应了，博卓卡斯替唤来出租马车。上车的时候，少年一个踉跄，张一零伸手扶着，才发现他的身体烫得吓人，估计已经病了不少日子。张一零扶他到车上躺下，少年在座位上昏睡过去。

在路上，博卓卡斯替问张一零：「你怎么知道我是谁？」

张一零说：「我们那里是小地方，没有什么娱乐，我把图书馆里面的报纸都看了。博卓卡斯替，血色山谷的弯刀，独当千军的英雄，报纸上有您的照片。」

博卓卡斯替苦笑了一下，说：「败军之将，何足言勇。不过我想告诉你，血色山谷殿后的部队，是一个排，但只有我活下来了。」

乌萨斯当年跟卡西米尔和维多利亚大战，最后战败，博卓卡斯替在血色山谷坚守，维多利亚皇家掷弹兵第八团不得寸进，乌萨斯第三集团军避免了覆亡的厄运。这当然是了不起的功勋，但是对当事人来说也未必是愉快的记忆。张一零是识趣的人。

马车驶到城寨外围就停下来，博卓卡斯替付了车钱，张一零把少年扶下车子，少年已经神智不清。

付过车钱，博卓卡斯替从行李中取出一件银色的披风披上，然后把患者抱了起来。

张一零认出了这件披风，「想不到您竟然是蜀山的教员。」

「你想不到的事情多着呢，张一零同学。」

「您居然知道我？」

「学院虽然扩招，但也只招了256个新生，要记下来不难。麻烦你帮我拿一下行李。」

九龙城寨[fn:4]，在龙门只需要说城寨——其实放眼世界，它都是独一无二的。从原有的居民楼生长出各种违章建筑让整个城寨变成了一个三维的迷宫。张一零漫步其中，不同的气味混合着潮湿的空气，令人作呕。但最令张一零难受的，不是空气，是目光，无处不在的目光。张一零能感觉到这些目光背后的怀疑和恶意。

他跟着博卓卡斯替穿行在城寨的小巷，最后来到一间诊所——准确来说，一间挂着诊所招牌的铺面，店铺里面有一桌人在打麻将。

「老朱，生意来了！」博卓卡斯替进门大喊。

一个头发稀疏，带着黑框眼镜的老头走了出来，他上身穿的白大褂破旧，没有系钮扣，露出里面褪色的旧汗衫，小腹微凸，下身只穿一条破旧的大短裤。他边走边说：「你他妈有什么好买卖给我？」

看见博卓卡斯替抱着的病人，他的脸更见阴沉，伸手探了一下病人的额头，然后瞧里屋大喊：「阿梅！」

一个瘦弱的姑娘走了出来，和这位朱医生一起把病人架入里屋。过了好一会，朱医生才出来。

「情况怎么样？」博卓卡斯替笑着问。

「不怎么样。」

「到底是什么病？」

「肺炎，外加营养不良。」

「那劳你费心了。」

「你他妈把钱付了！」

「咱们什么交情？居然谈钱。」张一零有点纳闷，博卓卡斯替居然有这么无赖的时候，不过可能是因为这个朱医生跟他关系密切吧。

「你可以再迟两天送过来，我绝对不收费。」

「要多少钱？」

「两百龙门币。」



* Footnotes

[fn:4] 这个不用注释都知道原型。 

[fn:3] 这里的地名和人名都来自《明日方舟》 。当然卡西米尔映射的是法国，维多利亚映射的是英国。

[fn:2] 这里埋了个伏笔，希望我能写到收回这个伏笔。 

[fn:1] 无容置疑，这是以《明日方舟》 的龙门作为蓝本的一个城市。
