#+TITLE: 逍遥游
#+OPTIONS: ^:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">
* 道别
「一零，我已经死了，我的丧礼在标准时12月7日零点开始，如果你有空就过来参加吧。」张一零的母亲坐在客厅的红木沙发上对着不存在的摄像头说。如果仔细听，可以听到厨房里面，小时候的他正和父亲一起做菜。

这是他7岁时候庆祝生日时的场景。那一天他和父亲烤了蛋糕和牛排，母亲在客厅调试刚买的三维录像仪。

那间房子后来卖了，就算没有在战争中被毁，估计也在战后荒废了。

「你父亲的事情，我欠你一个道歉。对不起。」这是母亲的影像最后一句话。

接受完这条视频信息，张一零断开了所有感官信号，让自己的意识滑如黑暗中。

「那不是道歉不道歉的事情，那只是一个心结，我和你都打不开。」张一零想对母亲这么说。
* 会议
张一零按时接入了天剑局[fn:1]的会议室。

张一零设置的会议室是一个普通的房间，与会者围坐着一张圆桌。这其实是他读大学时候学校辩论队的会议室。他比较怀旧。新一代的人甚至不打开视觉效果，直接接入信息流。

扶摇七[fn:2]天剑局目前有13个成员，加上每个成员的畸人[fn:3]，即使全部都视觉化也不会很拥挤。

人齐之后，局长老陈的畸人开始分发资料。张一零正在接受资料，2814给他发了一条私密通信：「你的情绪有点低落。发生什么事情了？」

2814[fn:4]是他的畸人，他的情感模块根据张一零的情绪反应调整过，这主要为了保证畸人与兀者[fn:5]能更契合，也为了保持畸人意识的多样性。

「家母逝世。」按照局里的规定，会议期间是要公开个人的情绪曲线的，他也最低限度地展示了一维情绪曲线，新生代的干员会更奔放一些，各个维度的曲线都会公开，有些人甚至会把生理指标都公开出来。

「节哀。」

这次会议主要的议程有两个，一个是统制派和回归派的冲突，另一个是扶摇七外的深安镇有一个叫王扶桑的人失踪了，镇长希望扶摇七协助调查。

从出生就开始接入秋水的人，自称「纯粹世代」，「纯粹世代」中出现了一种思潮，认为他们能跟秋水更好融合，有更快的信息处理能力，没有接入秋水的人应该接受他们的统治。这批人被称为统制派。回归派的思潮与之相反，认为人类因为走出秋水，回到其余的人中间。回归派的中坚是那些在秋水外出生的人，他们并非天生接入秋水。随着中坚年岁增长，势力消涨显而易见。

* Footnotes

[fn:5] 庄子《德充符》 ，「魯有兀者王駘，從之遊者，與仲尼相若」。

[fn:4] 绿灯侠设定中将宇宙分为3600个扇区，地球位于2814扇区。 

[fn:3] 庄子《大宗师》 ，「畸人者，畸於人而侔於天」。

[fn:2] 庄子《逍遥游》 ，「抟扶摇而上者九万里」。

[fn:1] 庄子《说剑》 中，有「天子剑、诸侯剑、庶人剑」的说法。
