#+TITLE: 《浓缩睡眠法》读书笔记
#+OPTIONS: ^:nil
#+HTML_HEAD: <link rel="stylesheet" href="https://latex.now.sh/style.css">

* 头部按摩
** 侧头部按摩
请用手掌的根部（掌根）在耳朵上方2厘米左右的位置，以画圈的方式按压6~10次。
** 按摩整个侧头部
请用除大拇指之外的4根手指抵在侧头部进行按摩放松。同样，按压力度以感到舒适为宜。
** 头顶部的按摩
5根手指在头顶一边慢慢画圈，一边用力按压再松开，并重复用力按压再松开的动作。
* 眼部
** 热敷
没微波炉，算了。
** 按摩
这不就是眼保健操么。
#+BEGIN_QUOTE
请先闭上眼睛，用大拇指侧面抵在眼球与眼球上方骨头之间的位置，然后轻柔按压眼球上方的骨头。

食指、中指、无名指搭在眼球下方的骨头上，然后轻柔地按压。按压3秒后松开3秒，重复3次。

最后，用食指、中指、无名指在太阳穴处画圈式按压放松。重复进行6~10次。
#+END_QUOTE
* 克服焦虑
** 输出不安写下愿望
#+BEGIN_QUOTE
将自己感到不安的事情写下来，如果是笔记本，请写在左边的页面上，如果是单张纸，请左右对折后展开，写在左半边的纸张上。

在笔记本的右边写下“理想中的好结果”，此处的重点是，要使用“已经”“了”“正在”等表现过去时或现在进行时的词语进行描述。
#+END_QUOTE
** 冥想
#+BEGIN_QUOTE
10分钟放松法。练习的时间放在睡前较为合适。花10分钟，聆听自己喜欢的音乐，缓慢地进行呼吸放松。

1分钟微冥想：闭上双眼，使用腹式呼吸法，用6秒吸气后，屏住呼吸3秒，再用10秒呼气。以此为1组，只需重复3组即可。
#+END_QUOTE
** 感谢与微笑
这两种方法太过玄学了，过。
* 改善身体
** 肩胛运动
#+BEGIN_QUOTE
这种方法非常简单。首先，将双手搭在肩膀上；然后手肘由前向后大幅度地转动，带动肩膀的旋转。

大约转动20次之后，你就能感受到原本僵硬的肌肉逐渐舒展开来，并且由于血液循环加强而感到身体变暖。（由前向后的转肩运动结束后，还要进行由后向前的转肩运动）
#+END_QUOTE
** 肩背部拉伸运动
要道具，不玩了（话说健身环也是有用的，可惜我出二手了）。
** 深蹲6次
上班摸鱼的时候玩（久坐之后做）。
* 改善习惯
